import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/layout/Header";
import { getCurrentSession } from "./action/auth";
import { SanityLive } from "@/sanity/lib/live";
import HeaderCategorySelector from "./components/layout/HeaderCategorySelector";
import Cart from "./components/cart/cart";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)=> {
  const { user } = await getCurrentSession();

  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-white min-h-[125vh] `}
      >
       <Header 
                    user={user}
                    categorySelector={<HeaderCategorySelector />}
                />
        {children}
        <Cart />
        <SanityLive />
      </body>
    </html>
  );
}
export default RootLayout